version: 2
updates:
  # For the app itself.
  - package-ecosystem: "nuget"
    directory: "/Source/Bluechirp/"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"
      - "backend"
      - "low priority"
    assignees:
      - "analogfeelings"
    reviewers:
      - "analogfeelings"
    commit-message:
      prefix: "[App -> All]"
      include: "scope"
    groups:
      community-toolkit:
        patterns:
          - "CommunityToolkit*"
      wasdk:
        patterns:
          - "Microsoft.Windows.SDK.BuildTools"
          - "Microsoft.WindowsAppSDK"
          - "WinUIEx"

  # For the common library.
  - package-ecosystem: "nuget"
    directory: "/Source/Bluechirp.Library/"
    schedule:
      interval: "daily"
    target-branch: "master"
    labels:
      - "dependencies"
      - "backend"
      - "low priority"
    assignees:
      - "analogfeelings"
    reviewers:
      - "analogfeelings"
    commit-message:
      prefix: "[Library -> All]"
      include: "scope"
    groups:
      community-toolkit:
        patterns:
          - "CommunityToolkit*"
      wasdk:
        patterns:
          - "Microsoft.Windows.SDK.BuildTools"
          - "Microsoft.WindowsAppSDK"
          - "WinUIEx"
