# This does not currently work.

name: UWP MSTest

on:
  push:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  workflow_dispatch:

jobs:
  run-unit-tests:
    strategy:
      matrix:
        configuration: [Release]
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      TargetPlatform: x64
      TargetConfig: Release
      CertificateFile: Bluechirp_Certificate.pfx
      SolutionPath: Bluechirp.sln
      TestsProjectNameEscaped: Bluechirp_Tests # It seems MSBuild doesn't like dots in names, replace with a _
      TestProjectPath: Source\Bluechirp.Tests\
      TestExecutablePath: Source\Bluechirp.Tests\bin\x64\Release\
      TestExecutableName: Bluechirp.Tests.build.appxrecipe

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.2.0
      
    - name: Restore Nuget Packages
      run: nuget restore ${{ env.SolutionPath }}
      
    - name: Decode the Pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.ENCODED_PFX_CERTIFICATE }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath $env:TestProjectPath -AdditionalChildPath $env:CertificateFile
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
      
    - name: Build Tests
      run: msbuild ${{ env.SolutionPath }} /p:Platform=${{ env.TargetPlatform }} /p:Configuration=${{ env.TargetConfig }} /target:${{ env.TestsProjectNameEscaped }} /p:PackageCertificateKeyFile=${{ env.CertificateFile }} /p:PackageCertificatePassword=${{ secrets.CERTIFICATE_KEY }}

    # Execute all unit tests in the solution
    - name: Execute Unit Tests
      uses: microsoft/vstest-action@v1.0.0
      with:
          testAssembly: ${{ env.TestExecutableName }}
          searchFolder: ${{ env.TestExecutablePath }}
          otherConsoleOptions: /Framework:frameworkUAP10 /Platform:${{ env.TargetPlatform }}
