name: UWP MSTest

on:
  push:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  workflow_dispatch:

jobs:
  run-unit-tests:
    strategy:
      matrix:
        configuration: [Release]
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      SolutionPath: Bluechirp.sln
      TargetPlatform: x64
      TestsProjectName: Bluechirp_Tests # It seems MSBuild doesn't like dots in names, replace with a _
      TestExecutablePath: Source\Bluechirp.Tests\bin\x64\Release\
      TestExecutableName: Bluechirp.Tests.exe

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build Tests
      run: msbuild ${{ env.SolutionPath }} /p:Platform=${{ env.TargetPlatform }} /target:${{ env.TestsProjectName }}

    # Execute all unit tests in the solution
    - name: Execute Unit Tests
      uses: microsoft/vstest-action@v1.0.0
      with:
          testAssembly: ${{ env.TestExecutableName }}
          searchFolder: ${{ env.TestExecutablePath }}
